version: '3'

services:

  nginx:
    image: nginx:1.17.2
    container_name: 'nginx-container-dev'
    restart: always
    working_dir: /app
    ports:
      - '8080:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../thumbs/:/app/thumbs
    links:
      - node-app-service

  node-app-service:
    build:
      context: .
      dockerfile: node-app.docker
    ports:
      - '3000:3000'
      - '9229:9229'
    working_dir: /app
    container_name: 'node-app-container-dev'
    volumes:
      - ../../:/app
      - ../../upload/:/app/upload
      - ../../thumbs/:/app/thumbs
    links:
      - mongodb-service
    command: 'npm run start:debug'
    hostname: 'node-app-service'
    environment:
      NODE_ENV: 'dev'
      APP_SECRET: 'change_it'
      MONGO_INITDB_DATABASE: 'qlp_practice'
      MONGO_REPLICASET: 'rs_qlp'
      MONGO_DATABASE_PORT: '27017'
      MONGO_POOL_SIZE: '200'
      PORT: '3000'
      EMAIL_LINK_HOST: 'localhost:4200'
      UPLOAD_DIRECTORY: '/app/upload'
      IMAGE_THUMB_DIRECTORY: '/app/thumbs'
      MAX_UPLOAD_FILE_SIZE: '7340032' # 7M
      MAIL_HOST: 'smtp.localhost.ru'
      MAIL_PORT: 25
      MAIL_USER: test
      MAIL_PASSWORD: test
      EMAIL_NO_REPLY: 'noreply@localhost.ru'
      SSL_KEY_FILE_PATH: ''
      SLL_CERT_FILE_PATH: ''


  mongodb-service:
    image: mongo:4.0.10-xenial
    container_name: 'mongo-db-container-dev'
    ports:
      - '30001:27017'
    restart: always
    volumes:
      - quick_lang_practice_db_dev:/data/db
    environment:
      MONGO_INITDB_DATABASE: 'qlp_practice'
    command: mongod --replSet rs_qlp

volumes:
  quick_lang_practice_db_dev:
